authors:
  duong-ngo:
    name: Ngo Quang Duong
    description: The maintainer of Unbounded Log
    avatar: https://avatars.githubusercontent.com/u/33195552
    slug: duong-ngo
    url: https://github.com/duong-ngo
